<?php

/**
 * This file is auto-generated from Nette generator. DO NOT EDIT!
 * (c) Travelport GDS 2008 All rights reserved.
 *  Proprietary Information of Travelport GDS.
 */

namespace TravelPortModule\Common;

use TravelPortModule\Common\BillingPointOfSaleInfo\CIDBNumberAType;

class BillingPointOfSaleInfo extends \Nette\Object
{

	/**
	 * @attribute
	 * @var string @value
	 *
	 * @xsdns TravelPortModule\Common
	 */
	protected $originApplication;

	/**
	 * @attribute
	 * @var \TravelPortModule\Common\BillingPointOfSaleInfo\CIDBNumberAType
	 * @xsdns TravelPortModule\Common
	 */
	protected $cIDBNumber;


	/**
	 * set attribute originApplication
	 * Name of the Point of Sale application which initiated the Request.This information will be provided as part of the provisioning of the user.
	 *
	 * @param string $value
	 *
	 * @return $this
	 */
	public function setOriginApplication($value)
	{
		$this->originApplication = $value;
		return $this;
	}


	/**
	 * get attribute originApplication
	 * Name of the Point of Sale application which initiated the Request.This information will be provided as part of the provisioning of the user.
	 *
	 * @return string
	 */
	public function getOriginApplication()
	{
		return $this->originApplication;
	}


	/**
	 * set attribute cIDBNumber
	 * A 10 Digit customer number generated by CIDB system.
	 *
	 * @param CIDBNumberAType $value
	 *
	 * @return $this
	 */
	public function setCIDBNumber($value = NULL)
	{
		if (NULL !== $value) {
		    $this->cIDBNumber = $value;
		}
		return $this;
	}


	/**
	 * get attribute cIDBNumber
	 * A 10 Digit customer number generated by CIDB system.
	 *
	 * @return string
	 */
	public function getCIDBNumber()
	{
		return $this->cIDBNumber;
	}

}
